"""业务服务模块"""

from app.services.rule_engine import (
    RuleEngine,
    RuleAction,
    RuleResult,
    SafetyCheck,
    SafetyInfo,
    HealthProfile,
    NutrientCandidate,
    DrugInteraction,
    AllergyRule,
    ChronicConditionRule,
    Severity,
    ALLERGY_RULES,
    CHRONIC_CONDITION_RULES,
    DRUG_INTERACTIONS,
)
from app.services.recommendation import (
    RecommendationEngine,
    RecommendationResult,
    RecommendationItem,
    HealthProfile as RecHealthProfile,
    LocalizedString,
    SafetyInfo as RecSafetyInfo,
    CommerceSlot,
    create_recommendation_engine,
    get_disclaimer,
    DISCLAIMER_ZH,
    DISCLAIMER_EN,
    NUTRIENT_DATABASE,
)
# 暂时注释掉这些服务的导入，因为它们依赖有循环导入问题的模型
# from app.services.commerce import (
#     CommerceService,
#     ShopifyClient,
#     SlotType,
#     ShopifyProductSchema,
#     PartnerOfferSchema,
#     CommerceSlotSchema,
#     SyncResult,
#     RedirectResult,
#     ClickEventData,
#     create_shopify_client,
#     create_commerce_service,
# )
# from app.services.analytics import (
#     AnalyticsService,
#     EventType,
#     EventDataSchema,
#     AnalyticsEventSchema,
#     EventListResponse,
#     EventSummary,
#     create_analytics_service,
# )
from app.services.config import (
    ConfigService,
    ConfigType,
    ConfigStatus,
    AuditAction,
    ConfigVersionSchema,
    AuditLogSchema,
    ConfigListResponse,
    InvalidStateTransitionError,
    ConfigNotFoundError,
    NoPreviousActiveVersionError,
    VALID_TRANSITIONS,
    create_config_service,
)
# 暂时注释掉 review 服务，因为它依赖旧的模型
# from app.services.review import (
#     ReviewService,
#     ReviewStatus,
#     RiskLevel,
#     ReviewAction,
#     ReviewQueueItemSchema,
#     ReviewListResponse,
#     ReviewFilterParams,
#     ReviewActionRequest,
#     CaseDetailSchema,
#     HealthProfileSchema,
#     QuestionAnswerSchema,
#     RecommendationItemSchema as ReviewRecommendationItemSchema,
#     ReviewNotFoundError,
#     InvalidReviewActionError,
#     HIGH_RISK_CONDITIONS,
#     HIGH_RISK_MEDICATIONS,
#     CRITICAL_ALLERGIES,
#     create_review_service,
# )

__all__ = [
    # Rule Engine
    "RuleEngine",
    "RuleAction",
    "RuleResult",
    "SafetyCheck",
    "SafetyInfo",
    "HealthProfile",
    "NutrientCandidate",
    "DrugInteraction",
    "AllergyRule",
    "ChronicConditionRule",
    "Severity",
    "ALLERGY_RULES",
    "CHRONIC_CONDITION_RULES",
    "DRUG_INTERACTIONS",
    # Recommendation Engine
    "RecommendationEngine",
    "RecommendationResult",
    "RecommendationItem",
    "RecHealthProfile",
    "LocalizedString",
    "RecSafetyInfo",
    "CommerceSlot",
    "create_recommendation_engine",
    "get_disclaimer",
    "DISCLAIMER_ZH",
    "DISCLAIMER_EN",
    "NUTRIENT_DATABASE",
    # Commerce Service - 暂时注释掉
    # "CommerceService",
    # "ShopifyClient",
    # "SlotType",
    # "ShopifyProductSchema",
    # "PartnerOfferSchema",
    # "CommerceSlotSchema",
    # "SyncResult",
    # "RedirectResult",
    # "ClickEventData",
    # "create_shopify_client",
    # "create_commerce_service",
    # Analytics Service - 暂时注释掉
    # "AnalyticsService",
    # "EventType",
    # "EventDataSchema",
    # "AnalyticsEventSchema",
    # "EventListResponse",
    # "EventSummary",
    # "create_analytics_service",
    # Config Service
    "ConfigService",
    "ConfigType",
    "ConfigStatus",
    "AuditAction",
    "ConfigVersionSchema",
    "AuditLogSchema",
    "ConfigListResponse",
    "InvalidStateTransitionError",
    "ConfigNotFoundError",
    "NoPreviousActiveVersionError",
    "VALID_TRANSITIONS",
    "create_config_service",
    # Review Service - 暂时注释掉
    # "ReviewService",
    # "ReviewStatus",
    # "RiskLevel",
    # "ReviewAction",
    # "ReviewQueueItemSchema",
    # "ReviewListResponse",
    # "ReviewFilterParams",
    # "ReviewActionRequest",
    # "CaseDetailSchema",
    # "HealthProfileSchema",
    # "QuestionAnswerSchema",
    # "ReviewRecommendationItemSchema",
    # "ReviewNotFoundError",
    # "InvalidReviewActionError",
    # "HIGH_RISK_CONDITIONS",
    # "HIGH_RISK_MEDICATIONS",
    # "CRITICAL_ALLERGIES",
    # "create_review_service",
]
