"""fix_analytics_columns

Revision ID: 443259ad8df3
Revises: 004
Create Date: 2026-01-21 11:43:40.892457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '443259ad8df3'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_products_created_at'), table_name='favorite_products')
    op.drop_index(op.f('ix_favorite_products_product_id'), table_name='favorite_products')
    op.drop_index(op.f('ix_favorite_products_user_id'), table_name='favorite_products')
    op.drop_table('favorite_products')
    op.drop_index(op.f('ix_quiz_history_created_at'), table_name='quiz_history')
    op.drop_index(op.f('ix_quiz_history_session_id'), table_name='quiz_history')
    op.drop_index(op.f('ix_quiz_history_user_id'), table_name='quiz_history')
    op.drop_table('quiz_history')
    op.add_column('products', sa.Column('click_cap', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('daily_cap', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('allowed_regions', postgresql.ARRAY(sa.String(length=10)), nullable=True))
    op.alter_column('users', 'account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_column('products', 'allowed_regions')
    op.drop_column('products', 'daily_cap')
    op.drop_column('products', 'click_cap')
    op.create_table('quiz_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('health_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommendations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ai_generated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quiz_history_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_history_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('quiz_history_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_quiz_history_user_id'), 'quiz_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_quiz_history_session_id'), 'quiz_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_quiz_history_created_at'), 'quiz_history', ['created_at'], unique=False)
    op.create_table('favorite_products',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('favorite_products_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('favorite_products_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('favorite_products_pkey')),
    sa.UniqueConstraint('user_id', 'product_id', name=op.f('uq_user_product'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_favorite_products_user_id'), 'favorite_products', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorite_products_product_id'), 'favorite_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_favorite_products_created_at'), 'favorite_products', ['created_at'], unique=False)
    # ### end Alembic commands ###
