"""add_user_otp_consent_quiz_tables

Revision ID: f4d93f004d5c
Revises: fc0f9c9a7643
Create Date: 2026-01-18 20:55:20.781458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4d93f004d5c'
down_revision: Union[str, None] = 'fc0f9c9a7643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('recipient_type', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_recipient'), 'otp_codes', ['recipient'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sessions_session_id'), 'quiz_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('is_agreed', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.drop_index(op.f('ix_recommendation_items_session_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index(op.f('ix_partner_offers_partner_id'), table_name='partner_offers')
    op.drop_table('partner_offers')
    op.drop_index(op.f('ix_audit_logs_config_version_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_question_answers_health_profile_id'), table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_recommendation_sessions_health_profile_id'), table_name='recommendation_sessions')
    op.drop_index(op.f('ix_recommendation_sessions_user_id'), table_name='recommendation_sessions')
    op.drop_table('recommendation_sessions')
    op.drop_index(op.f('ix_health_profiles_user_id'), table_name='health_profiles')
    op.drop_table('health_profiles')
    op.drop_index(op.f('ix_review_queue_session_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_commerce_clicks_recommendation_item_id'), table_name='commerce_clicks')
    op.drop_index(op.f('ix_commerce_clicks_session_id'), table_name='commerce_clicks')
    op.drop_index(op.f('ix_commerce_clicks_user_id'), table_name='commerce_clicks')
    op.drop_table('commerce_clicks')
    op.drop_index(op.f('ix_report_uploads_user_id'), table_name='report_uploads')
    op.drop_table('report_uploads')
    op.drop_index(op.f('ix_lab_metrics_health_profile_id'), table_name='lab_metrics')
    op.drop_index(op.f('ix_lab_metrics_report_upload_id'), table_name='lab_metrics')
    op.drop_table('lab_metrics')
    op.drop_index(op.f('ix_product_mappings_rec_key'), table_name='product_mappings')
    op.drop_table('product_mappings')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_config_versions_config_type'), table_name='config_versions')
    op.drop_table('config_versions')
    op.alter_column('ai_usage', 'call_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_products_supplement_id'), 'products', ['supplement_id'], unique=False)
    op.create_foreign_key(None, 'products', 'admin_users', ['partner_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_users_contact'), table_name='users')
    op.drop_constraint(op.f('users_contact_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'contact_type')
    op.drop_column('users', 'role')
    op.drop_column('users', 'contact')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('contact_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('mfa_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_contact_key'), 'users', ['contact'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_contact'), 'users', ['contact'], unique=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_supplement_id'), table_name='products')
    op.alter_column('ai_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_usage', 'call_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_table('config_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('config_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('rollout_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('change_reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='config_versions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_config_versions_config_type'), 'config_versions', ['config_type'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['recommendation_sessions.id'], name=op.f('analytics_events_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('analytics_events_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_events_pkey'))
    )
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_table('product_mappings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rec_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('slot_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('offer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['partner_offers.id'], name=op.f('product_mappings_offer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_mappings_pkey'))
    )
    op.create_index(op.f('ix_product_mappings_rec_key'), 'product_mappings', ['rec_key'], unique=False)
    op.create_table('lab_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('health_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_upload_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reference_range', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('flag', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['health_profile_id'], ['health_profiles.id'], name=op.f('lab_metrics_health_profile_id_fkey')),
    sa.ForeignKeyConstraint(['report_upload_id'], ['report_uploads.id'], name=op.f('lab_metrics_report_upload_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lab_metrics_pkey'))
    )
    op.create_index(op.f('ix_lab_metrics_report_upload_id'), 'lab_metrics', ['report_upload_id'], unique=False)
    op.create_index(op.f('ix_lab_metrics_health_profile_id'), 'lab_metrics', ['health_profile_id'], unique=False)
    op.create_table('report_uploads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('extracted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('report_uploads_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('report_uploads_pkey'))
    )
    op.create_index(op.f('ix_report_uploads_user_id'), 'report_uploads', ['user_id'], unique=False)
    op.create_table('commerce_clicks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recommendation_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('slot_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('commerce_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('clicked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('converted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recommendation_item_id'], ['recommendation_items.id'], name=op.f('commerce_clicks_recommendation_item_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['recommendation_sessions.id'], name=op.f('commerce_clicks_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('commerce_clicks_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('commerce_clicks_pkey'))
    )
    op.create_index(op.f('ix_commerce_clicks_user_id'), 'commerce_clicks', ['user_id'], unique=False)
    op.create_index(op.f('ix_commerce_clicks_session_id'), 'commerce_clicks', ['session_id'], unique=False)
    op.create_index(op.f('ix_commerce_clicks_recommendation_item_id'), 'commerce_clicks', ['recommendation_item_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolution_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['recommendation_sessions.id'], name=op.f('review_queue_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('review_queue_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('review_queue_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_review_queue_session_id'), 'review_queue', ['session_id'], unique=False)
    op.create_table('health_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('chronic_conditions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dietary_preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('budget_min', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('budget_max', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='health_profiles_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='health_profiles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_health_profiles_user_id'), 'health_profiles', ['user_id'], unique=False)
    op.create_table('recommendation_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('health_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('requires_review', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['health_profile_id'], ['health_profiles.id'], name='recommendation_sessions_health_profile_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='recommendation_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recommendation_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_recommendation_sessions_user_id'), 'recommendation_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendation_sessions_health_profile_id'), 'recommendation_sessions', ['health_profile_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('health_data_consent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('marketing_consent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('consented_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('consents_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consents_pkey'))
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('question_answers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('health_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['health_profile_id'], ['health_profiles.id'], name=op.f('question_answers_health_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('question_answers_pkey'))
    )
    op.create_index(op.f('ix_question_answers_health_profile_id'), 'question_answers', ['health_profile_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('config_version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('before_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('after_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('operator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['config_version_id'], ['config_versions.id'], name=op.f('audit_logs_config_version_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_index(op.f('ix_audit_logs_config_version_id'), 'audit_logs', ['config_version_id'], unique=False)
    op.create_table('partner_offers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('redirect_url', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('payout', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('cap', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_clicks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sponsored', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('partner_offers_pkey'))
    )
    op.create_index(op.f('ix_partner_offers_partner_id'), 'partner_offers', ['partner_id'], unique=False)
    op.create_table('recommendation_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rec_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('why_reasons', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('safety_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('commerce_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('commerce_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['recommendation_sessions.id'], name=op.f('recommendation_items_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recommendation_items_pkey'))
    )
    op.create_index(op.f('ix_recommendation_items_session_id'), 'recommendation_items', ['session_id'], unique=False)
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_session_id'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_otp_codes_recipient'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
